apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangout
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangout
      component: hangout
  template:
    metadata:
      labels:
        app: hangout
        component: hangout
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodegroup/hangout
                    operator: In
                    values:
                      - hangout
      imagePullSecrets:
        - name: docker-registry
      containers:
        - name: gohangout
          image: /gohangout:v1.1.1
          imagePullPolicy: Always
          workingDir: /etc/gohangout/
          command: ["/bin/bash", "-c", "/opt/gohangout/gohangout --config /etc/gohangout/conf.d/hangout.yaml -v 5 -pprof=true -pprof-address 0.0.0.0:8899 --worker 8 --logtostderr"]
          ports:
            - containerPort: 8899
              name: prof
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext: {}
          volumeMounts:
            - name: hangout-conf
              mountPath: /etc/gohangout/conf.d
      volumes:
      - name: hangout-conf
        configMap:
          name: hangout-conf
          items:
            - key: hangout.yaml
              path: hangout.yaml