apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hangout
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hangout
        component: hangout
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodegroup/hangout
                    operator: In
                    values:
                      - hangout
      imagePullSecrets:
        - name: docker-registry
      containers:
        - name: gohangout
          image: /gohangout:v1.1.1
          imagePullPolicy: Always
          workingDir: /etc/gohangout/
          command: ["/bin/bash", "-c", "/opt/gohangout/gohangout --config /etc/gohangout/conf.d/hangout.yaml -v 5 -pprof=true -pprof-address 0.0.0.0:8899 --worker 8 --logtostderr"]
          ports:
            - containerPort: 8899
              name: prof
          securityContext: {}
          volumeMounts:
            - name: hangout-config-volume
              mountPath: /etc/gohangout/conf.d
      volumes:
        - name: hangout-conf
          configMap:
            name: hangout-conf
            items:
              - key: hangout.yaml
                path: hangout.yaml