apiVersion: v1
kind: ConfigMap
metadata:
  name: hangout-conf
  namespace: default
  labels:
    app: hangout
data:
  hangout.yml: |-
    inputs:
        - Kafka:
            topic:
                basiclog-tlog_07_004: 6
            codec: json
            consumer_settings:
                bootstrap.servers: "192.168.01.02:9092,192.168.01.03:9092"
                group.id: logstash-es
                from.beginning: "false"
                max.partition.fetch.bytes: '10485760'
                auto.commit.interval.ms: '5000'
    filters:
        - Replace:
            fields:
              message: ['\\x', '\\\x']
        - Json:
            field: message
        #- Remove:
        #    fields: ['message']
    outputs:
        - Elasticsearch:
            hosts:
                - 'http://192.168.01.02:9200'
                - 'http://192.168.01.03:9200'
            index: '%{log_type}-%{+2006-01-02}'
            index_type: "log"
            index_time_location: 'Local'
            bulk_actions: 5000
            bulk_size: 5
            flush_interval: 60
            concurrent: 2
            retry_response_code: [401,502,429,505,500,503,404,403]